
namespace NovaVision.Hardware._007_SDK_LMI3DTool
{
    internal enum GoDataMessageTypes
    {
        GO_DATA_MESSAGE_TYPE_UNKNOWN = -1,
        GO_DATA_MESSAGE_TYPE_STAMP,
        GO_DATA_MESSAGE_TYPE_HEALTH,
        GO_DATA_MESSAGE_TYPE_VIDEO,
        GO_DATA_MESSAGE_TYPE_RANGE,
        GO_DATA_MESSAGE_TYPE_RANGE_INTENSITY,
        GO_DATA_MESSAGE_TYPE_PROFILE,
        GO_DATA_MESSAGE_TYPE_PROFILE_INTENSITY,
        GO_DATA_MESSAGE_TYPE_RESAMPLED_PROFILE,
        GO_DATA_MESSAGE_TYPE_SURFACE,
        GO_DATA_MESSAGE_TYPE_SURFACE_INTENSITY,
        GO_DATA_MESSAGE_TYPE_MEASUREMENT,
        GO_DATA_MESSAGE_TYPE_ALIGNMENT,
        GO_DATA_MESSAGE_TYPE_EXPOSURE_CAL
    }
}
