namespace NovaVision.Hardware._007_SDK_LMI3DTool
{
    internal enum GoOutputSource
    {
        GO_OUTPUT_SOURCE_NONE = 0,
        GO_OUTPUT_SOURCE_VIDEO = 1,
        GO_OUTPUT_SOURCE_RANGE = 2,
        GO_OUTPUT_SOURCE_PROFILE = 3,
        GO_OUTPUT_SOURCE_SURFACE = 4,
        GO_OUTPUT_SOURCE_SECTION = 9,
        GO_OUTPUT_SOURCE_RANGE_INTENSITY = 5,
        GO_OUTPUT_SOURCE_PROFILE_INTENSITY = 6,
        GO_OUTPUT_SOURCE_SURFACE_INTENSITY = 7,
        GO_OUTPUT_SOURCE_SECTION_INTENSITY = 10,
        GO_OUTPUT_SOURCE_MEASUREMENT = 8,
        GO_OUTPUT_SOURCE_TRACHEID = 9
    }

}
